// swaggerConfig.js
const swaggerJsdoc = require('swagger-jsdoc');
const path = require('path');

const options = {
  swaggerDefinition: {
    openapi: '3.0.0',
    info: {
      title: 'SPATIAL API Documentation',
      version: '1.0.0',
      description: 'API documentation generated by swagger-jsdoc',
    },
    servers: [
      {
        url: `http://${process.env.SERVER_HOST || 'localhost'}:${process.env.SERVER_PORT || 3000}`,
        description: 'Development server',
      },
    ],
  },
  apis: [
    path.join(__dirname, './routes/*.js'),
    // path.join(__dirname, './models/*.js'), // Uncomment and adjust if needed
  ],
  // Optional parameters if needed by your setup
  encoding: 'utf-8', // Encoding type
  failOnErrors: false,
  verbose: true,
  format: 'json',
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;
